// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Suporta tanto NEXT_PUBLIC_ (Next.js) quanto VITE_ (Vite) como fallback
const SUPABASE_URL = 
  process.env.NEXT_PUBLIC_SUPABASE_URL || 
  process.env.VITE_SUPABASE_URL || 
  '';

const SUPABASE_PUBLISHABLE_KEY = 
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || 
  process.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
  '';

// Validação com mensagem de erro mais clara
if (!SUPABASE_URL) {
  console.error('❌ Erro: NEXT_PUBLIC_SUPABASE_URL ou VITE_SUPABASE_URL não encontrada');
  console.error('📝 Crie um arquivo .env.local com: NEXT_PUBLIC_SUPABASE_URL=https://seu-projeto.supabase.co');
  throw new Error('Missing env.NEXT_PUBLIC_SUPABASE_URL or env.VITE_SUPABASE_URL');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.startsWith('http')) {
  console.error('❌ Erro: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY não encontrada ou inválida');
  console.error('📝 A chave deve ser a "anon public" key do Supabase, não a URL!');
  console.error('📝 Encontre em: Supabase Dashboard > Settings > API > Project API keys > anon public');
  throw new Error('Missing or invalid env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY. Should be the anon public key, not the URL.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});